name: Pytest Automation
on:
 push:
   branches: [ "master" ]
 pull_request:
   branches: [ "master" ]
jobs:
 tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: "3.11"
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
         pip install pytest pytest-cov
     - name: Run tests
       run: pytest -v -s -m smoke1 --maxfail=1 --disable-warnings --cov=. --html=1.html
     - name: Upload test results
       if: always()
       uses: actions/upload-artifact@v4
       with:
         name: pytest-results
         path: pytest-results.xml